name: Tag git deploy
description: forces a tag in git
inputs:

  deploy-tag:
    description: Tag to force


runs:
  using: composite
  steps:

    - name: Force push a deploy tag
      if: ${{ inputs.deploy-tag  }}
      id: force-push-tag
      shell: bash
      run: |
        git tag -f ${{ inputs.deploy-tag  }}
        git push --tags -f
        
        
