name: Test

on:
  push:
    paths:
      - 'src/scala/**'

jobs:
  test-query-services:
    runs-on:
      group: larger-runners
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and test query services
        run: |
          cd src/scala
          echo "Building and testing query-api and query-worker..."

          # Build both services
          ./gradlew :query-api:build :query-worker:build

          echo "Build completed successfully"

          # Show build artifacts
          echo "Build artifacts created:"
          find . -name "*.jar" -path "*/build/libs/*" | head -10

      - name: Run additional checks
        run: |
          cd src/scala
          echo "Running additional checks..."

          # Run any linting or additional validation
          # ./gradlew check

          echo "All checks passed"

      - name: Verify no Docker images were created
        run: |
          echo "Test workflow completed - no Docker images created"
          echo "This workflow only builds and tests the Java artifacts"
          echo "Use 'Build RC' workflow to create Docker images when needed"
