# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: z- Build a Go project

on:
  workflow_call:
    inputs:
      tag-to-build:
        type: string
        required: true
      go-version:
        type: string
        required: true


jobs:

  build-go:
    runs-on:
      group: larger-runners
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.tag-to-build }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache-dependency-path: "**/*.sum"

      - name: Find all go.mod files
        id: find-modules
        run: |
          # Find all directories containing go.mod files
          MOD_DIRS=$(find . -name 'go.mod' -exec dirname {} \;)
          echo "MOD_DIRS<<EOF" >> $GITHUB_ENV
          echo "$MOD_DIRS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build and test each module
        id: build-modules
        run: |
          
          MODULE_SOURCE_PATHS=$MOD_DIRS
          for i in $MODULE_SOURCE_PATHS; do \
            (echo ============ generating $i ... ; cd $i && go generate -v -n -x ./...)
          done
          
          for i in $MODULE_SOURCE_PATHS; do \
            (echo ============ building $i ... ; cd $i && go build ./...)
          done
          
          for i in $MODULE_SOURCE_PATHS; do \
            (echo ============ testing $i ... ; cd $i && go test ./...)
          done

